TERMUX_PKG_HOMEPAGE=http://www.openscenegraph.org/
TERMUX_PKG_DESCRIPTION="OpenSceneGraph git repository"
TERMUX_PKG_LICENSE="custom"
TERMUX_PKG_LICENSE_FILE="LICENSE.txt"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_GIT_BRANCH=master
TERMUX_PKG_VERSION="2022.12.02"
TERMUX_PKG_SRCURL="git+https://github.com/openscenegraph/OpenSceneGraph.git"
TERMUX_PKG_BUILD_IN_SRC=true
